name: Run Pre-Built and placed Rust API Exec on EC2

on:
  push:
    branches: [ "main" ] # This workflow triggers on pushes to the 'main' branch.

jobs:
  deploy:
    runs-on: ubuntu-latest # The job will run on a fresh Ubuntu runner provided by GitHub Actions.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checks out your repository code into the runner.
        # IMPORTANT: This step makes 'target/release/blazing_rust_000'
        # available on the runner *only if* it has been committed to your Git repo.

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # Configures AWS credentials for interacting with AWS services.
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Your AWS Access Key ID, stored as a GitHub secret.
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Your AWS Secret Access Key, stored as a GitHub secret.
          aws-region: ${{ secrets.AWS_REGION }} # Your AWS region, stored as a GitHub secret.

      - name: Connect to EC2 instance and Deploy API
        uses: appleboy/ssh-action@master # Uses the SSH action to connect to your EC2 instance and run commands.
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            FINAL_BINARY_PATH="$~/transfers/blazing_rust_000"
            
            sudo rm -rf /var/cache/nginx/*

            echo "Checking and killing processes on port 7000..."
            if command -v lsof >/dev/null 2>&1; then
              if sudo lsof -ti:7000; then
                echo "Killing processes on port 7000 using lsof..."
                sudo kill -9 $(sudo lsof -ti:7000)
              else
                echo "No process found listening on port 7000 using lsof."
              fi
            else
              echo "lsof not found, trying netstat..."
              if sudo netstat -tuln | grep :7000; then
                echo "Killing processes on port 7000 using netstat..."
                sudo kill -9 $(sudo netstat -tulnp | grep :7000 | awk '{print $7}' | cut -d'/' -f1)
              else
                echo "No process found listening on port 7000 using netstat."
              fi
            fi

            echo "Verifying executable at $FINAL_BINARY_PATH..."
            if [ ! -f "$FINAL_BINARY_PATH" ]; then
                echo "Error: Executable NOT found at $FINAL_BINARY_PATH. Cannot run."
                exit 1 # Fail the SSH step if the binary isn't there.
            fi
            
            sudo chmod +x "$FINAL_BINARY_PATH"
            echo "Executable permissions set."

            echo "Starting Rust API on port 7000 in a detached screen session..."
            sudo screen -S blazing_rust_000 "$FINAL_BINARY_PATH"
            

            echo "Restarting Nginx..."
            sudo systemctl restart nginx
            echo "Reloading Nginx configuration..."
            sudo systemctl reload nginx 

      - name: Wait for deployment
        run: |
          echo "Waiting 5 seconds for services to come online..."
          sleep 5